---
role:
  pkg:
    - name: ispell
      os: ["darwin"]
    # - slang # or ncursea
    # - name: urlview
    #   os: ["linux"]
    - lynx
    - name: mutt
      # os: ["!darwin"]
      # eventually install -–with-s-lang
      # and not --with-ui=ncurses?
    # - name: neomutt/neomutt/neomutt
    #   os: ["darwin"]
    #   --disable-fcntl
    #   --with-gpgme
    # - gpgme
    - isync
    # - khard
    # - mstmp
    # - mu
    # - ripmime
    # - w3m
    # - vdirsyncer
    # - pip3 install -I urlscan
  link:
    # - ".lynxrc"
    - ".mailcap"
    - ".muttrc" # Add line to source init instead?
    - ".mutt/colors/*:.mutt/colors" # Custom themes
    - ".mutt/accounts/*:.mutt/accounts"
    - ".mutt/aliases:.mutt"
  install:
    - "mkdir -p ~/.mutt/cache/{headers,bodies}"
