---
role:
  pkg:
    - name: ispell
      os: ["darwin"]
    # - slang # or ncursea
    # - name: urlview
    #   os: ["linux"]
    - lynx # - pandoc
    - procmail # for formail
    - name: mutt
      # os: ["!darwin"]
      # eventually install -–with-s-lang
      # and not --with-ui=ncurses?
    # - name: neomutt/neomutt/neomutt
    #   os: ["darwin"]
    #   --disable-fcntl
    #   --with-gpgme
    # - gpgme
    - isync # Requires ~/.mbsyncrc
    # - khard
    # - msmtp # Requires ~/.msmtprc
    - name: mu
      os: ["darwin"]
    - name: maildir-utils
      os: ["debian"]
    # - ripmime
    # - w3m
    # - vdirsyncer
    # - pip3 install -I urlscan
  dir:
    - .mutt
    - .mutt/cache/headers
    - .mutt/cache/bodies
    - .mutt/colors
    - .mutt/scripts
  link:
    # - ".lynxrc"
    - ".mailcap"
    - ".muttrc" # Add line to source init instead?
    - ".mutt/bindings:.mutt"
    - ".mutt/macros:.mutt"
    - ".mutt/colors/*:.mutt/colors" # Custom themes
    - ".mutt/scripts/*:.mutt/scripts"
  post_install:
    # - "mkdir -p ~/.mutt/cache/{headers,bodies}"
    - "if test ! -f ~/.mutt/aliases; then echo '# vi:ft=muttrc' > ~/.mutt/aliases; fi"
    # - "mu index --maildir ~/.mail"
  # cron:
  #   - test -f ~/.mbsyncrc && mbsync --all # --verbose
  #   - mu index --quiet # (on update: --rebuild)
  env:
    # maildir: ~/.mail
    tls_trust_file: '{{if eq .os "darwin" }}/usr/local/etc/openssl/cert.pem{{else}}/etc/ssl/certs/ca-certificates.crt{{end}}'
  template:
    - source: .mutt/account.tpl
      target: .mutt
      include_vars: ~/.mailrc.yml
    - source: .mbsyncrc.tpl
      include_vars: ~/.mailrc.yml
    - source: .msmtprc.tpl
      include_vars: ~/.mailrc.yml
    # - .bashrc: |
    #   # Set GPG TTY
    #   export GPG_TTY=$(tty)

    #   # Refresh gpg-agent tty in case user switches into an X session
    #   gpg-connect-agent updatestartuptty /bye >/dev/null
