---
role:
  pkg:
    - name: ispell
      os: ["darwin"]
    # - slang # or ncursea
    # - name: urlview
    #   os: ["linux"]
    - lynx
    - name: mutt
      # os: ["!darwin"]
      # eventually install -–with-s-lang
      # and not --with-ui=ncurses?
    # - name: neomutt/neomutt/neomutt
    #   os: ["darwin"]
    #   --disable-fcntl
    #   --with-gpgme
    # - gpgme
    - isync # Requires ~/.mbsyncrc
    # - khard
    # - msmtp # Requires ~/.msmtprc
    - mu # (maildir-utils)
    # - ripmime
    # - w3m
    # - vdirsyncer
    # - pip3 install -I urlscan
  link:
    # - ".lynxrc"
    - ".mailcap"
    - ".muttrc" # Add line to source init instead?
    - ".mutt/aliases:.mutt"
    - ".mutt/macros:.mutt"
    - ".mutt/accounts/*:.mutt/accounts"
    - ".mutt/colors/*:.mutt/colors" # Custom themes
    - ".mutt/scripts/*:.mutt/scripts"
  install:
    - "mkdir -p ~/.mutt/cache/{headers,bodies}"
    # - "mu index --maildir ~/.mail"
    # - ""
  # cron:
  #   - test -f ~/.mbsyncrc && mbsync --all # --verbose
  #   - mu index --quiet # (on update: --rebuild)
  # env:
  #   maildir: ~/.mail
