#!/usr/bin/env bash

# http://nosubstance.me/post/mutt-secret-sauce/
# https://github.com/oblitum/dotfiles/blob/ArchLinux/.local/bin/MIMEmbellish
# https://github.com/wincent/wincent/blob/master/roles/dotfiles/files/.mutt/scripts/msmtp.rb

set -e

# Msmtp Queue Binary
MSMTPQ=~/.mutt/scripts/msmtpq

TMPFILE=/tmp/mutt.sendmail # $(mktemp)

# Save the message to a file
cat - > "$TMPFILE"

# TMPFILE=/tmp/sendmail.msmtpq
# echo "$(date) --------------" >> "$TMPFILE"
# cat - >> "$TMPFILE"

# # Extract the date header
# DATE=$(formail -xDate: < "$TMPFILE")
# # Convert to the current timezone (defined by TZ)
# DATE=$(date -R -d "$DATE")
# # Output the modified message
# echo "Date: $DATE"

# formail -fI Date < "$TMPFILE" | $MSMTPQ "$@"
$MSMTPQ "$@"

# Clean up
# rm -f "$TMPFILE"
