#!/usr/bin/env bash

set -e

# Msmtp Queue Binary
MSMTPQ=~/.mutt/scripts/msmtpq

# TMPFILE=$(mktemp)

# Save the message to a file
cat - > "$TMPFILE"

# TMPFILE=/tmp/sendmail.msmtpq
# echo "$(date) --------------" >> "$TMPFILE"
# cat - >> "$TMPFILE"

# # Extract the date header
# DATE=$(formail -xDate: < "$TMPFILE")
# # Convert to the current timezone (defined by TZ)
# DATE=$(date -R -d "$DATE")
# # Output the modified message
# echo "Date: $DATE"

# formail -fI Date < "$TMPFILE" | $MSMTPQ "$@"
$MSMTPQ "$@"

# Clean up
rm -f "$TMPFILE"
